name: ci-php-workflow
on: 
  pull_request:
    branches:
      - dev

jobs:
  check-app:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     php: ['8.1', '8.2']
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          php_version: ${{ matrix.php }}
          configuration: ./

      #Docker build    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: farofapereira/fullcycle-integracao-continua:latest